#!/usr/bin/python3
# -*- coding: utf-8 -*-

import sys
import os
import os.path
import webbrowser

if "." not in sys.path:
    sys.path.append(".")

import default_settings as settings  # Overriden in load_config()

if __name__ == "__main__":
    settings.load_config(globals())
    try:
        tmp_file = sys.argv[1]
    except IndexError:
        "No file path given"
    finally:
        # Rename to omit spamming browser history
        rss_file = os.path.join(os.path.dirname(tmp_file), "rss.tmp")
        os.rename(tmp_file, rss_file)

        # Open site with default browser
        webbrowser.open('{protocol}://{domain}:{port}/?file={rss_file}'.format(
            protocol= "https" if settings.SSL else "http",
            domain=settings.HOST,
            port=settings.PORT,
            rss_file=rss_file)
        )
